# Generated by Django 2.0.6 on 2018-06-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='type',
            field=models.IntegerField(choices=[(1, 'Savings'), (2, 'Expense')], default=1, max_length=1),
        ),
    ]
